#
# https://gitlab.com/gitlab-org/gitlab-foss/tree/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml
#
image: node:22-alpine

# Cache modules in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/

before_script:
    - npm ci

build_stage :
    stage: build
    script:
        - npm run build
    when: on_success

e2e_tests :
    image : node:22-alpine
    stage: test
    script:
        # - npm run ng e2e
        - echo "No e2e testing yet"

unit_test:
    image: node:22-alpine
    stage : test
    script :
        # - npm run ng test
        - echo "No unit testing yet"

deployment_stage:
    stage: deploy
    script:
        - echo "Configure deployement here"